version: '3'
services:
  app:
    build: .
    image: shinn1r0/auto_search_lesson
    volumes:
      - "./app:/root/app"
      - "./.env:/root/.env"
    working_dir: /root
    environment:
      PYTHONPATH: "/root:/root/app"
      PYTHONIOENCODIND: utf_8
      PIPENV_DOTENV_LOCATION: /root/.env
      TZ: Asia/Tokyo
    restart: unless-stopped
    privileged: true
    logging:
      driver: gcplogs
    command: /bin/sh -c "python -u /root/app/main.py"
