version: '3'
services:
  app:
    build: .
    volumes:
      - "./app:/root/app"
      - "./logs:/root/logs"
      - "./.env:/root/.env"
    working_dir: /root
    environment:
      PYTHONPATH: "/root/app"
      PYTHONIOENCODIND: utf_8
      PIPENV_DOTENV_LOCATION: /root/.env
      TZ: Asia/Tokyo
    restart: unless-stopped
    command: /bin/sh -c "python /root/app/main.py >> /root/logs/main_log.txt"